[window]

opacity = 0.75 
blur = true

padding.x = 10
padding.y = 10

title = "Alacritty"
dynamic_title = false

[font]

normal = { family = "RecMonoLinear Nerd Font Mono", style = "Regular"}
bold = { family = "RecMonoLinear Nerd Font Mono", style = "Bold"}
italic = { family = "RecMonoLinear Nerd Font Mono", style = "Italic"}
bold_italic = { family = "RecMonoLinear Nerd Font Mono", style = "Bold Italic"}

size =  15.0
